# This is a basic workflow to help you get started with Actions

name: Continues Development

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    name: Build Continues Development
    runs-on: ubuntu-latest
    steps:
      - name: Continues Deployment API Bimtama
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            echo "CD to folder project"
            cd /var/www/bimtama-api
            echo "Reset Git to the latest commit"
            git reset --hard origin/main
            echo "Pull Rebase"
            git pull origin main --rebase
            echo "NPM I if available new package"
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            echo "First we kill instance PM2 for saving memory"
            pm2 del bimtama-api
            npm --help
            npm i
            echo "Re-build Application"  
            pm2 start npm --name bimtama-api -- start
